//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidTrackerDesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidTrackerDesktopApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Country&quot;: &quot;Barbados&quot;,
        ///    &quot;Slug&quot;: &quot;barbados&quot;,
        ///    &quot;ISO2&quot;: &quot;BB&quot;
        ///  },
        ///  {
        ///    &quot;Country&quot;: &quot;Gibraltar&quot;,
        ///    &quot;Slug&quot;: &quot;gibraltar&quot;,
        ///    &quot;ISO2&quot;: &quot;GI&quot;
        ///  },
        ///  {
        ///    &quot;Country&quot;: &quot;Lithuania&quot;,
        ///    &quot;Slug&quot;: &quot;lithuania&quot;,
        ///    &quot;ISO2&quot;: &quot;LT&quot;
        ///  },
        ///  {
        ///    &quot;Country&quot;: &quot;Malaysia&quot;,
        ///    &quot;Slug&quot;: &quot;malaysia&quot;,
        ///    &quot;ISO2&quot;: &quot;MY&quot;
        ///  },
        ///  {
        ///    &quot;Country&quot;: &quot;Nauru&quot;,
        ///    &quot;Slug&quot;: &quot;nauru&quot;,
        ///    &quot;ISO2&quot;: &quot;NR&quot;
        ///  },
        ///  {
        ///    &quot;Country&quot;: &quot;Palestinian Territory&quot;,
        ///    &quot;Slug&quot;: &quot;palestine&quot;,
        ///    &quot;ISO2&quot;: &quot;PS&quot;
        ///  },
        ///  {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries_json {
            get {
                return ResourceManager.GetString("countries-json", resourceCulture);
            }
        }
    }
}
